In [2]:
print('Hola')

Hola


In [3]:
print('Still testing Kernel/Terminal functionality')

Still testing Kernel/Terminal functionality


In [5]:
%pip install tensorflow -v

  Using cached tensorflow-2.18.0-cp312-cp312-win_amd64.whl.metadata (3.3 kB)
  Using cached tensorflow_intel-2.18.0-cp312-cp312-win_amd64.whl.metadata (4.9 kB)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.2.10-py2.py3-none-any.whl.metadata (875 bytes)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached termcolor-2.5.0-py3-none-any.whl.metadata (6.1 kB)
  Using cached grpcio-1.70.0-cp312-cp312-win_amd64.whl.metadata (4.0 kB)
  Using cached tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
  Using cached keras-3.8.0-py3-none-any.whl.metadata (5.8 kB)
  Using cached ml_dtypes-0.4.1-cp312-cp312-win_amd64.whl.metadata (20 kB)
  Using 

In [7]:
%pip install tensorflow keras --progress-bar on

In [8]:
import tensorflow as tf

In [9]:
print(tf.__version__)

2.18.0


In [10]:
scalar = tf.constant(6)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [11]:
scalar.ndim

0

In [12]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [13]:
vector.ndim

1

In [14]:
matrix = tf.constant([[18.9, 67], [5., 8], [9., 6]], dtype='float64')

In [16]:
# Creating Random Tensors

# Representation : patterns, features, weights

In [19]:
random_1 = tf.random.Generator.from_seed(42) # seed is for reproducibiiity
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42) # seed is for reproducibiiity
random_2 = random_2.uniform(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [21]:
# Are they equal?

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [44]:
# Shuffling the order of a tensor


not_shuffled = tf.constant([[12,3], [30,4], [5, 6]])

# Shuffle our non-shuffled tensor
shuffled = tf.random.shuffle(not_shuffled, seed=42)

shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  6],
       [30,  4],
       [12,  3]])>

In [46]:
# Creating tensors from NumPy Arrays

tf.random.set_seed(42) # Global level shuffle
tf.random.shuffle(not_shuffled, seed=42) # Operation level shuffling

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12,  3],
       [30,  4],
       [ 5,  6]])>

In [47]:
# Other ways to make tensors

tf.ones([8, 7])

<tf.Tensor: shape=(8, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [48]:
tf.zeros(shape=(3, 7))

<tf.Tensor: shape=(3, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [60]:
# Getting attributes from tensors

# Attributes could include shape, size, rank, dimension

rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [61]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [63]:
# Number of dimensions ; Rank

rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [64]:
# Expanding the tensor

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [66]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [70]:
rank_2_tensor = tf.constant([
    [10, 7], [3, 7]
])

rank_2_tensor.shape, rank_2_tensor.ndim, tf.size(rank_2_tensor)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [73]:
rank_2_tensor[:, :1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[10],
       [ 3]])>

In [ ]:
# Expanding tensors

rank_3_tensor = rank_2_tensor[..., tf.newaxis]

rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 7]]])>

In [76]:
tf.expand_dims(rank_2_tensor, axis=-1) # expand at the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 7]]])>

In [ ]:
# Tensor manipulating using operations

tensor = tf.constant([
    [10, 7], [8, 9]
])

tensor + 19

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[29, 26],
       [27, 28]])>

In [78]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 80,  90]])>

In [79]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [18, 19]])>

In [80]:
tf.subtract(tensor, 9)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1, -2],
       [-1,  0]])>

In [81]:
tf.divide(tensor, 4)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2.5 , 1.75],
       [2.  , 2.25]])>

In [86]:
# Matrix Multiplication

tensor_1 = tf.constant([
    [3, 4, 5], [6, 6, 8], [3, 3, 3]
])

tensor_2 = tf.constant([
    [4, 8], [7, 5], [9, 0]
])

tf.linalg.matmul(tensor_1, tensor_2)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 85,  44],
       [138,  78],
       [ 60,  39]])>

In [87]:
tensor_1 @ tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 85,  44],
       [138,  78],
       [ 60,  39]])>

In [88]:
tensor_1_float64 = tf.cast(tensor_1, dtype=tf.float64)
tensor_1_float64

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[3., 4., 5.],
       [6., 6., 8.],
       [3., 3., 3.]])>

In [95]:
import tensorflow as tf

tensor_1 = tf.constant([
    [3, 4, 5], 
    [6, 6, 8], 
    [3, 3, 3]
], dtype=tf.float64)  # Ensure float64 type if needed

tensor_2 = tf.constant([
    [1, 2], 
    [3, 4], 
    [5, 6]
], dtype=tf.float64)

# Check shapes
print("Shape of tensor_1:", tensor_1.shape)  # (3, 3)
print("Shape of tensor_2:", tensor_2.shape)  # (3, 2)

# Adjust axes for correct dot product
result = tf.tensordot(tensor_1, tensor_2, axes=1)

print("Result shape:", result.shape)  # Expected: (3, 2)
print(result)


Shape of tensor_1: (3, 3)
Shape of tensor_2: (3, 2)
Result shape: (3, 2)
tf.Tensor(
[[40. 52.]
 [64. 84.]
 [27. 36.]], shape=(3, 2), dtype=float64)


In [96]:
tf.tensordot(tensor_1, tensor_2, axes=1)

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[40., 52.],
       [64., 84.],
       [27., 36.]])>

In [98]:
# Aggregating tensors; finding mean, median and mode

tf.abs(tf.subtract(tensor_1, 19))

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[16., 15., 14.],
       [13., 13., 11.],
       [16., 16., 16.]])>

In [119]:
import numpy as np

nums = tf.constant(np.random.randint(0, 100, size=50), dtype=tf.float32)
nums

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([51., 12., 13.,  5., 21., 51., 70., 83., 64., 91., 36.,  9., 80.,
       95., 42., 90., 42., 81.,  2., 81., 19., 36., 31., 72., 19., 36.,
       21., 86., 23., 97., 77.,  1., 96., 45.,  8., 95., 74., 87., 12.,
       63., 18., 42., 30.,  3.,  2., 55.,  5., 80.,  5., 82.],
      dtype=float32)>

In [120]:
tf.reduce_min(nums)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [121]:
np.min(nums)

1.0

In [122]:
tf.reduce_max(nums).numpy()

97.0

In [123]:
tf.reduce_mean(nums)

<tf.Tensor: shape=(), dtype=float32, numpy=46.779998779296875>

In [124]:
tf.reduce_sum(nums)

<tf.Tensor: shape=(), dtype=float32, numpy=2339.0>

In [125]:
# %pip install tf_keras -v


In [126]:
# %pip install tensorflow_probability --progress-bar on

import tensorflow_probability as tfp

tfp.stats.variance(nums)

<tf.Tensor: shape=(), dtype=float32, numpy=1042.7315673828125>

In [127]:
tf.math.reduce_std(nums)

<tf.Tensor: shape=(), dtype=float32, numpy=32.29135513305664>

In [128]:
tf.math.reduce_variance(nums)

<tf.Tensor: shape=(), dtype=float32, numpy=1042.7315673828125>

In [129]:
# Finding positional maximum and minimum

tf.argmax(nums)

<tf.Tensor: shape=(), dtype=int64, numpy=29>

In [130]:
tf.argmin(nums)

<tf.Tensor: shape=(), dtype=int64, numpy=31>

In [131]:
tf.argsort(nums)

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([31, 18, 44, 43,  3, 46, 48, 34, 11,  1, 38,  2, 40, 20, 24,  4, 26,
       28, 42, 22, 10, 21, 25, 14, 16, 41, 33,  0,  5, 45, 39,  8,  6, 23,
       36, 30, 12, 47, 17, 19, 49,  7, 27, 37, 15,  9, 13, 35, 32, 29])>

In [135]:
# Squeezing a tensor

uniform_nums = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
uniform_nums

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
           0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
           0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
           0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
           0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
           0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
           0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
           0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
           0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
           0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062]]]]],
      dtype=float32)>

In [136]:
uniform_nums_squeezed = tf.squeeze(uniform_nums)

uniform_nums_squeezed, uniform_nums_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
        0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
        0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
        0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
        0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
        0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
        0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
        0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
        0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
        0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062],
       dtype=float32)>,
 TensorShape([50]))

In [162]:
# One hot encoding
some_list = [1, 2,3, 4, 5]
# tf.one_hot(nums.numpy(), depth=4)[0]

In [163]:
tf.one_hot(some_list, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [164]:
tf.one_hot(some_list, depth=5, on_value=2, off_value=3)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[3, 2, 3, 3, 3],
       [3, 3, 2, 3, 3],
       [3, 3, 3, 2, 3],
       [3, 3, 3, 3, 2],
       [3, 3, 3, 3, 3]])>

In [165]:
H = tf.range(1, 5)

In [169]:
H = tf.cast(H, dtype=tf.float32)

In [170]:
tf.sqrt(H)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.       , 1.4142135, 1.7320508, 2.       ], dtype=float32)>

In [171]:
tf.math.log(H)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.       , 0.6931472, 1.0986123, 1.3862944], dtype=float32)>

In [174]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]